### ISSUE TITLE
Support Altis Autoloader

### ISSUE THREAD

**Issue by kucrut** [humanmade/asset-loader#15]
See [Altis documentation](https://www.altis-dxp.com/resources/docs/getting-started/custom-modules/).

**Comment by kadamwhite** [comment]
@kucrut This plugin is now bundled within `altis/cms`. Do you feel this is still needed? I don't see a lot of value in adding this if it's already available in the platform.

**Comment by kucrut** [comment]
No, I don't think this is needed anymore.
