### ISSUE TITLE
Incorrect load order for inline CSS when hot reloading

### ISSUE THREAD

**Issue by johnbillion** [humanmade/asset-loader#20]
Given an enqueued stylesheet that also includes some inline CSS, the main stylesheet incorrectly takes precedence over the inline CSS when using dev mode (eg. with Webpack dev server from Webpack Helpers).

## Example

Given a theme's `style.css` that contains the following (make paragraphs red):

```css
p { color: red; }
```

Use the following to enqueue the style and then add an inline style that uses the same specificity selector (make paragraphs green):

```php
add_action( 'wp_enqueue_scripts', function() {

    \Asset_Loader\autoenqueue(
        get_template_directory() . '/build/asset-manifest.json',
        // style.css - https://github.com/humanmade/asset-loader/issues/1
        'style.js',
        [
            'handle' => 'my-style',
        ]
    );

    wp_add_inline_style( 'my-style', 'p { color: green; }' );
} );
```

When loading the site with the Webpack dev server running, the inline style will not take precedence as it should (your paragraphs will unexpectedly be red). This appears to be due to the way that Webpack dev server loads the CSS is as JavaScript.

I've not looked into the root cause but Ryan suggested this might be due to Asset Loader not telling style-loader about which `<link>` element it should be replacing. Needs confirming.

**Comment by kadamwhite** [comment]
Unfortunately this is a sideeffect of how the Webpack DevServer works, and cannot be solved in this plugin or in our webpack helpers library.

What's happening is that, in development, Webpack generates CSS files as a JS module which injects inline CSS into the document. On a hot reload, that CSS is swapped out, causing the new styles to take effect as the browser recomputes the cascade.

There is, therefore, no sense of "load order" within DevServer when dealing with CSS: All CSS from a Webpack-managed bundle will get written to the header _after_ any inline CSS.

I regret that I see no way to work around this behavior, and therefore don't think this is a solvable bug. To test CSS which has to be overridden by `wp_add_inline_style` it may be necessary to forego DevServer entirely.

I'm going to close this out as unfixable, but if a solution occurs to anybody please open a new issue to resurrect the discussion!

**Comment by sambulance** [comment]
Just to note here that I also ran into this when working with third-party enqueued styles. After building out a feature that was dependant on those styles, the change in cascade meant my styles were broken once built. This was remedied by setting the third-party stylesheet as a dependency of mine, but I was very confused trying to figure out what caused it.

> There is, therefore, no sense of "load order" within DevServer when dealing with CSS

This is pretty fundamental to the way CSS works. I would expect any dev tools to preserve the order that assets are enqueued. This could cause considerable headaches and additional work, both in this instance where building assets created bugs, but also potentially fixing issues that wouldn't exist for built assets.

If this is not something we can solve directly, perhaps we need to raise this higher up the chain. As John/Ryan said, it should be possible to swap out the link tag for a style tag.
