### ISSUE TITLE
Publish releases on GitHub, or remove existing ones

### ISSUE THREAD

**Issue by johnbillion** [humanmade/asset-loader#34]
When you view [the repo front page](https://github.com/humanmade/asset-loader) it looks like the latest version is 0.3.4 because that was the latest tag that has a published release for it. There are subsequent tags for 0.4.0, 0.4.1, and 0.5.0.

Options:

1. Publish a release for the new tags and keep doing so
2. Delete the existing releases and stick to just tagging

---

<img width="181" alt="" src="https://user-images.githubusercontent.com/208434/111187427-40a38d80-85b4-11eb-8198-a4dcd3b5669f.png">

**Comment by kadamwhite** [comment]
I've set up a release for v0.5 and will do so for subsequent versions (and encourage others to do the same if they run the release process). I was unaware that tags didn't get auto-promoted to Releases, thank you for the issue clarifying the difference.

**Comment by kadamwhite** [comment]
@Sephsekla has created a release for 0.6 as well
