### ISSUE TITLE
Do not fatal if manifest is missing (type hinting)

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/asset-loader#41]
(extracted from a comment on #40)

Probably the biggest risk / gotcha I run into regularly with Asset Loader right now is that if you try to enqueue a file and there is no manifest on disk, `get_asset_manifest()` returns `null` which is not a string which causes a 500. 

```
Argument 1 passed to Asset_Loader\enqueue_asset() must be of the type string, null given
```

This is a rough edge we should probably smooth off, by one or more of

- removing the type constraint
- making the manifest function return an empty string instead of null
- and possibly log a warning within `(enqueue|register)_asset` if the manifest is missing

I'm personally most in favor of removing the constraint and possibly adding an error, but curious for thoughts. @Sephsekla et al

**Comment by Sephsekla** [comment]
I think the biggest issue is that it's inconsistent with the behaviour of `wp_enqueue_script` tbh. In a way I kinda like the fatal, since you'll immediately know about it if a critical asset is missing.

What do you think about some kind of strict mode flag/argument which lets a user decide whether it fatally errors?

**Comment by kadamwhite** [comment]
Not particularly font of strict modes, it's another layer you need to keep in mind on top of environment, WP_Debug, etc. 🤔 

My rough stance here is that there's many things that can cause a build to fail, and I wouldn't want the site to fatal if a plugin was activated without a build process in place or in a situation where assets didn't get omitted as expected. On the sort of sites we work on, as an example, if we were adding a blocks plugin I'd consider it much more desirable to have the site load _sans_ those blocks than to fail to load entirely.

**Comment by kadamwhite** [comment]
Fixed in https://github.com/humanmade/asset-loader/pull/59
